apiVersion: "v1"
kind: Pod
metadata:
   name: test-pd
spec: 
  containers: 
  -   image: test-webserver
      name: test-container
      volumeMounts:
      - mountPath: /my-nfs-data
        name: test-volume
  volumes:
  - name: test-volume
    nfs:
      server: my-nfs-server.example.com
      path: /my-nfs-volume
      readOnly: true         