apiVersion: v1
kind: ResourceQuota
metadata:
   name: mem-cpu-quota
   namespace: qos-example
spec:
   hard:
     requests.cpu: 1
     requests.memory: 1Gi
     limits.cpu: 2
     limits.memory: 2Gi   